### ISSUE TITLE
crash：很抱歉， "APatch"已停止运行

### ISSUE THREAD

**Issue by a1489632** [bmax121/APatch#579]
### Please check before submitting an issue/在提交 issue 前请检查

- [X] I have searched the issues and haven't found anything relevant/我已经搜索了 issues 列表，没有发现于本问题相关内容
- [X] If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch/修复失败或刷入修补后镜像不能启动，请前往 KernelPatch 提问
- [X] I will upload bugreport file in APatch Manager - Settings - Report log/我会上传 bureport 文件从 APatch 管理器 - 设置 - 发送日志
- [X] I know how to reproduce the issue which may not be specific to my device/我知道如何重新复现这个问题

### Version requirement/版本要求

- [X] I am using latest CI version of APatch/我正在使用最新 CI 版本

### Describe the bug/描述 bug

最新ci版本10763-124-g6c2a981 修补，选择boot.img后直接闪退

Release最新版不闪退但是无法修补，提示CONFIG_KALLSYMS_ALL=n

### Reproduce method/复现方法

-1. 打开APatch
-2. 修补
-3. 选择boot.img
-4. 闪退

### Expected behavior/预期行为

修补，并生成一个修补后的boot.img

### Actual behaviour /实际行为

闪退

### Logs/日志
[APatch_bugreport_2024-08-02_18_16.tar.gz](https://github.com/user-attachments/files/16469232/APatch_bugreport_2024-08-02_18_16.tar.gz)
上面是APatch设置导出的日志
下面这个日志是我用Termux+Magisk Root抓的日志
```
~ $ ./tsu_for_vivo
.../files/home # cd
~ # logcat -c
~ # logcat -c
~ # logcat|grep AndroidRuntime
08-02 18:01:05.480 13319 13388 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
08-02 18:01:05.480 13319 13388 E AndroidRuntime: Process: me.bmax.apatch, PID: 13319
08-02 18:01:05.480 13319 13388 E AndroidRuntime: java.io.FileNotFoundException: kpimg
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    at android.content.res.AssetManager.nativeOpenAsset(Native Method)
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    at android.content.res.AssetManager.open(AssetManager.java:834)
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    at android.content.res.AssetManager.open(AssetManager.java:811)
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    at fP.u(Unknown Source:186)
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    at Ja.o(Unknown Source:5)
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    at Rn.run(Unknown Source:111)
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    at o2.run(Unknown Source:42)
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    at K50.run(Unknown Source:2)
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    at Bk.run(Unknown Source:91)
08-02 18:01:05.480 13319 13388 E AndroidRuntime:    Suppressed: Ym: [pm{Cancelling}@bf23e69, Dispatchers.IO]
^C
~ #
```

### Device Name/设备名称

PD2057C (vivo y52s)

### OS Version/系统版本

PD2057C_A_1.16.14

### APatch Version/APatch 版本

10763-124-g6c2a981

### Kernel Version/内核版本

4.14.141

### KernelPatch Version/KernelPatch 版本

n/a

### Additional context/其他信息

n/a

**Comment by a1489632** [comment]
8月3日最新CI已修复。
